
let dashboardRawData = [];
let dashboardSortColumn = 'shared_name';
let dashboardSortDirection = 'asc';
let printersFetchController = null;
let printersPollInterval = null;
const PRINTERS_POLL_MS = 30000;
let discoveredPrintersCache = [];
let hostnameLookupController = null;
let savedPrintersSortColumn = 'id';
let savedPrintersSortDirection = 'asc';
let countersAutoTimer = null;
let currentAddressBookPrinter = null;

function showTab(tabName){document.querySelectorAll('.tab').forEach(tab=>tab.classList.remove('active'));const selected=document.getElementById(tabName);if(selected)selected.classList.add('active');if(tabName==='dashboard'){startPrintersPolling();loadPrinters();}else{stopPrintersPolling();}if(tabName==='printers')loadSavedPrinters();if(tabName==='counters')loadCounters();if(tabName==='inventory')loadInventory();if(tabName==='tonerControl')loadTonerControl();}
function togglePrinterSection(sectionId){['manualPrinterCard','discoverPrinterCard'].forEach(id=>{const el=document.getElementById(id);if(!el)return;if(id===sectionId)el.classList.toggle('is-open');else el.classList.remove('is-open');});}
function toggleDashboardFilters(){const panel=document.getElementById('dashboardFilters');const icon=document.getElementById('filterToggleIcon');const state=document.getElementById('filterToggleState');const btn=document.getElementById('dashboardFilterBtn');const closed=panel.classList.toggle('closed');if(btn)btn.classList.toggle('is-open',!closed);if(icon)icon.textContent=closed?'▾':'▴';if(state)state.textContent=closed?'Ocultos':'Visibles';}
function toggleDashboardFullscreen(){const root=document.documentElement;const sidebar=document.querySelector('.sidebar');const btnLabel=document.getElementById('fullscreenBtnLabel');const btnIcon=document.getElementById('fullscreenBtnIcon');const viewMode=document.getElementById('viewMode');const setUi=isFs=>{document.body.classList.toggle('fullscreen',isFs);if(sidebar)sidebar.style.display=isFs?'none':'';if(viewMode&&isFs)viewMode.value='table';if(btnLabel)btnLabel.textContent=isFs?'Salir pantalla':'Pantalla completa';if(btnIcon)btnIcon.textContent=isFs?'🗗':'⛶';if(isFs)loadPrinters();setTimeout(()=>{setTableFullHeight();},80);};if(document.fullscreenElement){document.exitFullscreen().then(()=>setUi(false)).catch(err=>console.error('No se pudo salir de pantalla completa:',err));return;}root.requestFullscreen().then(()=>setUi(true)).catch(err=>console.error('No se pudo activar pantalla completa:',err));}
document.addEventListener('fullscreenchange',()=>{const isFs=!!document.fullscreenElement;const sidebar=document.querySelector('.sidebar');const btnLabel=document.getElementById('fullscreenBtnLabel');const btnIcon=document.getElementById('fullscreenBtnIcon');const viewMode=document.getElementById('viewMode');document.body.classList.toggle('fullscreen',isFs);if(sidebar)sidebar.style.display=isFs?'none':'';if(viewMode&&isFs)viewMode.value='table';if(btnLabel)btnLabel.textContent=isFs?'Salir pantalla':'Pantalla completa';if(btnIcon)btnIcon.textContent=isFs?'🗗':'⛶';setTimeout(()=>{setTableFullHeight();if(isFs)loadPrinters();},80);});
function setDensityMode(mode){document.body.classList.remove('density-compact','density-standard','density-large');document.body.classList.add(mode==='compact'?'density-compact':mode==='large'?'density-large':'density-standard');}
function isValidIpv4(ip){return /^(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}$/.test((ip||'').trim());}
function setFieldValidation(inputId,helpId,message='',state=''){const input=document.getElementById(inputId);const help=document.getElementById(helpId);if(!input)return;input.classList.remove('input-valid','input-invalid');if(state==='valid')input.classList.add('input-valid');if(state==='invalid')input.classList.add('input-invalid');if(help){help.textContent=message;help.className=`field-help${state==='invalid'?' error':state==='valid'?' success':''}`;}}
function validatePrinterIpField(){const ip=document.getElementById('printerIp')?.value.trim()||'';if(!ip){setFieldValidation('printerIp','printerIpHelp','');return false;}if(!isValidIpv4(ip)){setFieldValidation('printerIp','printerIpHelp','IP inválida','invalid');return false;}setFieldValidation('printerIp','printerIpHelp','IP válida','valid');return true;}
function toggleDiscoverModeFields(){const mode=document.getElementById('discoverMode')?.value||'range';const startWrap=document.getElementById('discoverStartWrap');const endWrap=document.getElementById('discoverEndWrap');const singleWrap=document.getElementById('discoverSingleWrap');if(startWrap)startWrap.style.display=mode==='range'?'':'none';if(endWrap)endWrap.style.display=mode==='range'?'':'none';if(singleWrap)singleWrap.style.display=mode==='ip'?'':'none';}
function validateDiscoverFields(){const mode=document.getElementById('discoverMode')?.value||'range';const startIp=document.getElementById('discoverStartIp')?.value.trim()||'';const endIp=document.getElementById('discoverEndIp')?.value.trim()||'';const singleIp=document.getElementById('discoverSingleIp')?.value.trim()||'';let valid=true;if(mode==='range'){if(!startIp||!isValidIpv4(startIp)){setFieldValidation('discoverStartIp','discoverStartIpHelp','IP inicial inválida','invalid');valid=false;}else setFieldValidation('discoverStartIp','discoverStartIpHelp','OK','valid');if(!endIp||!isValidIpv4(endIp)){setFieldValidation('discoverEndIp','discoverEndIpHelp','IP final inválida','invalid');valid=false;}else setFieldValidation('discoverEndIp','discoverEndIpHelp','OK','valid');}else{setFieldValidation('discoverStartIp','discoverStartIpHelp','');setFieldValidation('discoverEndIp','discoverEndIpHelp','');if(!singleIp||!isValidIpv4(singleIp)){setFieldValidation('discoverSingleIp','discoverSingleIpHelp','IP inválida','invalid');valid=false;}else setFieldValidation('discoverSingleIp','discoverSingleIpHelp','OK','valid');}return valid;}
async function autofillPrinterNameFromIp(){const ipEl=document.getElementById('printerIp');const nameEl=document.getElementById('printerName');const communityEl=document.getElementById('printerCommunity');if(!ipEl||!nameEl)return;const ip=ipEl.value.trim();const community=(communityEl?.value||'public').trim()||'public';if(!isValidIpv4(ip))return;if(hostnameLookupController){try{hostnameLookupController.abort();}catch(e){}}hostnameLookupController=new AbortController();try{const response=await fetch(`/printers/resolve-hostname?ip=${encodeURIComponent(ip)}&community=${encodeURIComponent(community)}`,{signal:hostnameLookupController.signal});const data=await response.json();if(data?.hostname&&!nameEl.value.trim()){nameEl.value=data.hostname;nameEl.dataset.autoFilled='true';}}catch(error){if(error.name!=='AbortError')console.warn('No se pudo resolver el hostname.',error);}finally{hostnameLookupController=null;}}
function safeValue(value){if(value===null||value===undefined||value==='')return null;const n=Number(value);return Number.isNaN(n)?null:n;}
function tonerAlertText(value){if(value===null)return '';if(value<10)return '<div class="critical-text">Crítico: tóner muy bajo</div>';if(value<30)return '<div class="warning-text">Advertencia: tóner bajo</div>';return '';}
function renderTonerBar(label,value,cssClass){const numeric=safeValue(value);const display=numeric===null?'-':`${numeric}%`;const width=numeric===null?0:Math.max(0,Math.min(100,numeric));return `<div class="toner-item"><div class="toner-label-row"><span>${label}</span><span>${display}</span></div><div class="bar"><div class="bar-fill ${cssClass}" style="width:${width}%"></div></div>${label==='Black'?tonerAlertText(numeric):''}</div>`;}
function renderTonerMini(label,value,cssClass){const numeric=safeValue(value);if(numeric===null)return `<span class="tc-muted">-</span>`;const width=Math.max(0,Math.min(100,numeric));return `<div class="toner-mini" title="${label}: ${numeric}%"><div class="mini-bar"><div class="fill ${cssClass}" style="width:${width}%"></div></div><span class="mini-label">${numeric}%</span></div>`;}
function normalizeErrorType(errorText){const text=(errorText||'Sin error').toLowerCase();if(!text||text==='sin error')return 'ok';if(text.includes('crítico')||text.includes('critical'))return 'critical';if(text.includes('low toner')||text.includes('tóner bajo'))return 'low';return 'other';}
function getErrorClass(errorText,status){if((status||'').toLowerCase()!=='online')return 'error-critical';const type=normalizeErrorType(errorText);if(type==='critical')return 'error-critical';if(type==='low')return 'error-warn';if(type==='other')return 'error-critical';return 'error-ok';}
function buildCard(printer){const status=(printer.status||'offline').toLowerCase();const statusClass=status==='online'?'status-online':'status-offline';const shared=printer.shared_name||'Sin shared name';const nameLine=printer.name?`<div class="printer-secondary">${printer.name}</div>`:'';let tonerHtml=renderTonerBar('Black',printer.toner_black,'bar-black');if(printer.is_color){tonerHtml+=renderTonerBar('Cyan',printer.toner_cyan,'bar-cyan');tonerHtml+=renderTonerBar('Magenta',printer.toner_magenta,'bar-magenta');tonerHtml+=renderTonerBar('Yellow',printer.toner_yellow,'bar-yellow');}return `<div class="card"><div class="card-header"><div><div class="printer-name">${shared}</div>${nameLine}<div class="printer-model">${printer.model??'-'}</div></div><div class="status-pill ${statusClass}">${status==='online'?'ONLINE':'OFFLINE'}</div></div><div class="info-row"><strong>Serie:</strong> ${printer.serial??'-'}</div><div class="info-row"><strong>IP:</strong> ${printer.ip??'-'}</div><div class="info-row"><strong>Ubicación:</strong> ${printer.location??'-'}</div><div class="info-row"><strong>Error:</strong> <span class="${getErrorClass(printer.error_message,printer.status)}">${printer.error_message??'Sin error'}</span></div><div class="info-row"><strong>Tipo:</strong> ${printer.is_color?'Color':'Blanco y negro'}</div><div class="toner-section"><div class="toner-title">Consumibles</div>${tonerHtml}</div></div>`;}
function buildDashboardTableRow(printer){const status=(printer.status||'offline').toLowerCase();const statusHtml=status==='online'?`<span class="status-badge status-badge-online">Online</span>`:`<span class="status-badge status-badge-offline">Offline</span>`;const errorClass=getErrorClass(printer.error_message,printer.status);const errorText=printer.error_message||'Sin error';const normalized=normalizeErrorType(printer.error_message);let rowClass='';if(status!=='online')rowClass='row-error';else if(normalized==='critical')rowClass='row-error';else if(normalized==='low')rowClass='row-low';const tonerPieces=[renderTonerMini('K',printer.toner_black,'bar-black')];if(printer.is_color){tonerPieces.push(renderTonerMini('C',printer.toner_cyan,'bar-cyan'));tonerPieces.push(renderTonerMini('M',printer.toner_magenta,'bar-magenta'));tonerPieces.push(renderTonerMini('Y',printer.toner_yellow,'bar-yellow'));}return `<tr class="${rowClass}"><td>${printer.shared_name??'-'}</td><td>${printer.name??'-'}</td><td>${printer.model??'-'}</td><td>${printer.serial??'-'}</td><td>${printer.ip??'-'}</td><td>${statusHtml}</td><td class="${errorClass}">${errorText}</td><td><div class="toner-inline">${tonerPieces.join('')}</div></td></tr>`;}
function compareDashboardValues(a,b,column){const av=((a[column]??'')+'').toLowerCase().trim();const bv=((b[column]??'')+'').toLowerCase().trim();if(column==='ip'){const aip=av.split('.').map(x=>parseInt(x||'0',10));const bip=bv.split('.').map(x=>parseInt(x||'0',10));for(let i=0;i<4;i++){if((aip[i]||0)<(bip[i]||0))return -1;if((aip[i]||0)>(bip[i]||0))return 1;}return 0;}return av.localeCompare(bv);}
function sortDashboardTableColumns(data){const sorted=[...data];sorted.sort((a,b)=>{let result=compareDashboardValues(a,b,dashboardSortColumn);if(dashboardSortDirection==='desc')result*=-1;return result;});return sorted;}
function toggleTableSort(column){if(dashboardSortColumn===column){dashboardSortDirection=dashboardSortDirection==='asc'?'desc':'asc';}else{dashboardSortColumn=column;dashboardSortDirection='asc';}loadPrinters();}
function getDashboardRelevance(printer){const status=(printer.status||'offline').toLowerCase();const errorText=(printer.error_message||'Sin error').toLowerCase();const black=safeValue(printer.toner_black);let score=0;if(status!=='online')score+=100;if(errorText.includes('crítico')||errorText.includes('critical'))score+=80;else if(errorText.includes('low toner')||errorText.includes('tóner bajo'))score+=40;else if(errorText!=='sin error')score+=20;if(black!==null)score+=Math.max(0,100-black);return score;}
function normalizeErrorType(errorText){const text=(errorText||'Sin error').toLowerCase();if(!text||text==='sin error')return 'ok';if(text.includes('crítico')||text.includes('critical'))return 'critical';if(text.includes('low toner')||text.includes('tóner bajo'))return 'low';return 'other';}
function getErrorClass(errorText,status){if((status||'').toLowerCase()!=='online')return 'error-critical';const type=normalizeErrorType(errorText);if(type==='critical')return 'error-critical';if(type==='low')return 'error-warn';if(type==='other')return 'error-critical';return 'error-ok';}
function buildCard(printer){const status=(printer.status||'offline').toLowerCase();const statusClass=status==='online'?'status-online':'status-offline';const shared=printer.shared_name||'Sin shared name';const nameLine=printer.name?`<div class="printer-secondary">${printer.name}</div>`:'';let tonerHtml=renderTonerBar('Black',printer.toner_black,'bar-black');if(printer.is_color){tonerHtml+=renderTonerBar('Cyan',printer.toner_cyan,'bar-cyan');tonerHtml+=renderTonerBar('Magenta',printer.toner_magenta,'bar-magenta');tonerHtml+=renderTonerBar('Yellow',printer.toner_yellow,'bar-yellow');}return `<div class="card"><div class="card-header"><div><div class="printer-name">${shared}</div>${nameLine}<div class="printer-model">${printer.model??'-'}</div></div><div class="status-pill ${statusClass}">${status==='online'?'ONLINE':'OFFLINE'}</div></div><div class="info-row"><strong>Serie:</strong> ${printer.serial??'-'}</div><div class="info-row"><strong>IP:</strong> ${printer.ip??'-'}</div><div class="info-row"><strong>Ubicación:</strong> ${printer.location??'-'}</div><div class="info-row"><strong>Error:</strong> <span class="${getErrorClass(printer.error_message,printer.status)}">${printer.error_message??'Sin error'}</span></div><div class="info-row"><strong>Tipo:</strong> ${printer.is_color?'Color':'Blanco y negro'}</div><div class="toner-section"><div class="toner-title">Consumibles</div>${tonerHtml}</div></div>`;}
function buildDashboardTableRow(printer){const status=(printer.status||'offline').toLowerCase();const statusHtml=status==='online'?`<span class="status-badge status-badge-online">Online</span>`:`<span class="status-badge status-badge-offline">Offline</span>`;const errorClass=getErrorClass(printer.error_message,printer.status);const errorText=printer.error_message||'Sin error';const normalized=normalizeErrorType(printer.error_message);let rowClass='';if(status!=='online')rowClass='row-error';else if(normalized==='critical')rowClass='row-error';else if(normalized==='low')rowClass='row-low';const tonerPieces=[renderTonerMini('K',printer.toner_black,'bar-black')];if(printer.is_color){tonerPieces.push(renderTonerMini('C',printer.toner_cyan,'bar-cyan'));tonerPieces.push(renderTonerMini('M',printer.toner_magenta,'bar-magenta'));tonerPieces.push(renderTonerMini('Y',printer.toner_yellow,'bar-yellow'));}return `<tr class="${rowClass}"><td>${printer.shared_name??'-'}</td><td>${printer.name??'-'}</td><td>${printer.model??'-'}</td><td>${printer.serial??'-'}</td><td>${printer.ip??'-'}</td><td>${statusHtml}</td><td class="${errorClass}">${errorText}</td><td><div class="toner-inline">${tonerPieces.join('')}</div></td></tr>`;}
function compareDashboardValues(a,b,column){const av=((a[column]??'')+'').toLowerCase().trim();const bv=((b[column]??'')+'').toLowerCase().trim();if(column==='ip'){const aip=av.split('.').map(x=>parseInt(x||'0',10));const bip=bv.split('.').map(x=>parseInt(x||'0',10));for(let i=0;i<4;i++){if((aip[i]||0)<(bip[i]||0))return -1;if((aip[i]||0)>(bip[i]||0))return 1;}return 0;}return av.localeCompare(bv);}
function sortDashboardTableColumns(data){const sorted=[...data];sorted.sort((a,b)=>{let result=compareDashboardValues(a,b,dashboardSortColumn);if(dashboardSortDirection==='desc')result*=-1;return result;});return sorted;}
function toggleTableSort(column){if(dashboardSortColumn===column){dashboardSortDirection=dashboardSortDirection==='asc'?'desc':'asc';}else{dashboardSortColumn=column;dashboardSortDirection='asc';}loadPrinters();}
function getDashboardRelevance(printer){const status=(printer.status||'offline').toLowerCase();const errorText=(printer.error_message||'Sin error').toLowerCase();const black=safeValue(printer.toner_black);let score=0;if(status!=='online')score+=100;if(errorText.includes('crítico')||errorText.includes('critical'))score+=80;else if(errorText.includes('low toner')||errorText.includes('tóner bajo'))score+=40;else if(errorText!=='sin error')score+=20;if(black!==null)score+=Math.max(0,100-black);return score;}
function ipToNumber(ip){return String(ip||'').split('.').reduce((acc,part)=>(acc*256)+(parseInt(part,10)||0),0);}
function sortDashboardData(data,sortValue){const sorted=[...data];sorted.sort((a,b)=>{const sharedA=(a.shared_name||'').toLowerCase();const sharedB=(b.shared_name||'').toLowerCase();const nameA=(a.name||'').toLowerCase();const nameB=(b.name||'').toLowerCase();const modelA=(a.model||'').toLowerCase();const modelB=(b.model||'').toLowerCase();if(sortValue==='relevance_desc')return getDashboardRelevance(b)-getDashboardRelevance(a);if(sortValue==='relevance_asc')return getDashboardRelevance(a)-getDashboardRelevance(b);if(sortValue==='shared_name_asc')return sharedA.localeCompare(sharedB);if(sortValue==='shared_name_desc')return sharedB.localeCompare(sharedA);if(sortValue==='name_asc')return nameA.localeCompare(nameB);if(sortValue==='name_desc')return nameB.localeCompare(nameA);if(sortValue==='model_asc')return modelA.localeCompare(modelB);if(sortValue==='model_desc')return modelB.localeCompare(modelA);if(sortValue==='ip_asc')return ipToNumber(a.ip)-ipToNumber(b.ip);if(sortValue==='ip_desc')return ipToNumber(b.ip)-ipToNumber(a.ip);return 0;});return sorted;}
async function loadPrinters(){try{if(printersFetchController){try{printersFetchController.abort();}catch(e){}}printersFetchController=new AbortController();const response=await fetch('/printers/status',{signal:printersFetchController.signal});let data=await response.json();if(!Array.isArray(data))data=[];const search=(document.getElementById('searchInput')?.value||'').toLowerCase().trim();const statusFilter=document.getElementById('statusFilter')?.value||'all';const typeFilter=document.getElementById('typeFilter')?.value||'all';const errorFilter=document.getElementById('errorFilter')?.value||'all';const sortFilter=document.getElementById('sortFilter')?.value||'relevance_desc';const viewMode=document.getElementById('viewMode')?.value||'table';if(search){data=data.filter(p=>((p.shared_name||'')+' '+(p.name||'')+' '+(p.ip||'')+' '+(p.model||'')+' '+(p.serial||'')).toLowerCase().includes(search));}data=data.filter(p=>{const status=(p.status||'').toLowerCase();const errorType=normalizeErrorType(p.error_message);const matchesStatus=statusFilter==='all'||(statusFilter==='online'&&status==='online')||(statusFilter==='offline'&&status!=='online');const matchesType=typeFilter==='all'||(typeFilter==='color'&&!!p.is_color)||(typeFilter==='mono'&&!p.is_color);const matchesError=errorFilter==='all'||
(p.error_message||'Sin error').toLowerCase().includes(errorFilter);return matchesStatus&&matchesType&&matchesError;});data=sortDashboardData(data,sortFilter);data=sortDashboardTableColumns(data);dashboardRawData=[...data];const cardsView=document.getElementById('dashboardCardsView');const tableView=document.getElementById('dashboardTableView');const grid=document.getElementById('printersGrid');const tableBody=document.getElementById('dashboardTableBody');grid.innerHTML='';tableBody.innerHTML='';if(!data.length){grid.innerHTML='<div class="empty-state">No hay impresoras para mostrar con esos filtros.</div>';tableBody.innerHTML='<tr><td colspan="8">No hay impresoras para mostrar.</td></tr>';document.getElementById('totalPrinters').textContent='0';document.getElementById('onlinePrinters').textContent='0';document.getElementById('offlinePrinters').textContent='0';document.getElementById('lowTonerPrinters').textContent='0';document.getElementById('lastUpdate').textContent='Sin datos';}else{let onlineCount=0,offlineCount=0,lowTonerCount=0;data.forEach(printer=>{const status=(printer.status||'offline').toLowerCase();if(status==='online')onlineCount++;else offlineCount++;const black=safeValue(printer.toner_black);if(black!==null&&black<30)lowTonerCount++;if(viewMode==='cards'){const t=document.createElement('template');t.innerHTML=buildCard(printer).trim();if(t.content.firstElementChild)grid.appendChild(t.content.firstElementChild);}else{tableBody.insertAdjacentHTML('beforeend',buildDashboardTableRow(printer));}});document.getElementById('totalPrinters').textContent=String(data.length);document.getElementById('onlinePrinters').textContent=String(onlineCount);document.getElementById('offlinePrinters').textContent=String(offlineCount);document.getElementById('lowTonerPrinters').textContent=String(lowTonerCount);document.getElementById('lastUpdate').textContent='Actualizado: '+new Date().toLocaleTimeString();}cardsView.style.display=viewMode==='cards'?'block':'none';tableView.style.display=viewMode==='table'?'block':'none';}catch(error){if(error.name!=='AbortError')console.error('loadPrinters error:',error);}finally{printersFetchController=null;}}
function startPrintersPolling(){stopPrintersPolling();loadPrinters();printersPollInterval=setInterval(()=>{const dash=document.getElementById('dashboard');if(dash&&dash.classList.contains('active'))loadPrinters();},PRINTERS_POLL_MS);}function stopPrintersPolling(){if(printersPollInterval){clearInterval(printersPollInterval);printersPollInterval=null;}if(printersFetchController){try{printersFetchController.abort();}catch(e){}printersFetchController=null;}}
function resetFilters(){document.getElementById('searchInput').value='';document.getElementById('statusFilter').value='all';document.getElementById('typeFilter').value='all';document.getElementById('errorFilter').value='all';document.getElementById('sortFilter').value='relevance_desc';document.getElementById('viewMode').value='table';loadPrinters();}
function getSelectedDiscoveredPrinters(){return discoveredPrintersCache.filter((_,index)=>document.getElementById(`discoverSelect_${index}`)?.checked);}
function toggleAllDiscovered(checked){discoveredPrintersCache.forEach((_,index)=>{const checkbox=document.getElementById(`discoverSelect_${index}`);if(checkbox)checkbox.checked=checked;});}
function clearDiscoveredPrinters(){discoveredPrintersCache=[];const list=document.getElementById('printersList');const selectAll=document.getElementById('selectAllDiscovered');if(list)list.innerHTML='<tr><td colspan="7">Configure la búsqueda y presione buscar.</td></tr>';if(selectAll)selectAll.checked=false;}
function openAddressBook(printer){currentAddressBookPrinter=printer||null;const title=document.getElementById('addressBookPrinterTitle');const meta=document.getElementById('addressBookPrinterMeta');const status=document.getElementById('addressBookStatus');const displayName=printer?.shared_name||printer?.name||printer?.model||'Impresora';if(title)title.textContent=`Libreta de direcciones - ${displayName}`;if(meta)meta.textContent=`IP: ${printer?.ip??'-'} | Modelo: ${printer?.model??'-'} | Serie: ${printer?.serial??'-'}`;if(status)status.textContent='Cargando libreta de direcciones local segura...';showTab('addressBook');loadAddressBookEntries();}
function showAddressBookPendingMessage(){const status=document.getElementById('addressBookStatus');if(status)status.textContent=currentAddressBookPrinter?`Pendiente conectar la libreta real de ${currentAddressBookPrinter.ip}. Actualmente está usando almacenamiento local seguro.`:'Abra primero una impresora desde el botón amarillo de la tabla.';}
async function loadAddressBookEntries(){const list=document.getElementById('addressBookList');const status=document.getElementById('addressBookStatus');if(!currentAddressBookPrinter){if(list)list.innerHTML='<tr><td colspan="12">Seleccione una impresora.</td></tr>';showAddressBookPendingMessage();return;}try{if(list)list.innerHTML='<tr><td colspan="12">Cargando libreta de direcciones...</td></tr>';const response=await fetch(`/printers/${currentAddressBookPrinter.id}/address-book`);const data=await response.json();if(!response.ok)throw new Error(data.detail||'No se pudo cargar la libreta');const entries=Array.isArray(data.entries)?data.entries:[];if(status)status.textContent=`Modo: ${data.storage_mode||'local-safe'} | Registros: ${entries.length}`;if(!entries.length){list.innerHTML='<tr><td colspan="12">No hay usuarios registrados.</td></tr>';return;}list.innerHTML='';entries.forEach(entry=>{const entryJson=JSON.stringify(entry).replace(/'/g,'&apos;');list.innerHTML+=`<tr><td>${entry.registration_no??'-'}</td><td>${entry.name??'-'}</td><td>${entry.key_display??'-'}</td><td>${entry.freq?'Sí':'No'}</td><td>${entry.title1??'-'}</td><td>${entry.title2??'-'}</td><td>${entry.title3??'-'}</td><td>${entry.user_code??'-'}</td><td>${entry.email_address??'-'}</td><td>${entry.folder??'-'}</td><td>${entry.status??'-'}</td><td><div class="action-row" style="margin-bottom:0;"><button class="action-button" onclick='editAddressBookEntry(${entryJson})'>Editar</button><button class="action-button action-button-danger" onclick="deleteAddressBookEntry('${entry.registration_no}')">Eliminar</button></div></td></tr>`;});}catch(error){if(list)list.innerHTML='<tr><td colspan="12">No se pudo cargar la libreta de direcciones.</td></tr>';if(status)status.textContent=error.message||'Error cargando libreta';console.error(error);}}
function normalizeAddressBookPromptValue(value){const trimmed=(value??'').trim();return trimmed?trimmed:null;}
async function createAddressBookEntry(){if(!currentAddressBookPrinter){showAddressBookPendingMessage();return;}const name=prompt('Nombre del usuario:');if(name===null)return;const payload={name:name.trim(),key_display:normalizeAddressBookPromptValue(prompt('Key Display:',name.trim())),freq:(prompt('Frecuente? (si/no):','si')||'si').trim().toLowerCase()!=='no',title1:normalizeAddressBookPromptValue(prompt('Title 1:','')),title2:normalizeAddressBookPromptValue(prompt('Title 2:','')),title3:normalizeAddressBookPromptValue(prompt('Title 3:','')),user_code:normalizeAddressBookPromptValue(prompt('User Code:','')),email_address:normalizeAddressBookPromptValue(prompt('E-mail Address:','')),folder:normalizeAddressBookPromptValue(prompt('Folder:','')),status:normalizeAddressBookPromptValue(prompt('Status:','Activo'))||'Activo'};if(!payload.name){alert('El nombre es obligatorio.');return;}try{const response=await fetch(`/printers/${currentAddressBookPrinter.id}/address-book`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.detail||'No se pudo agregar el usuario');await loadAddressBookEntries();}catch(error){alert(error.message||'No se pudo agregar el usuario.');console.error(error);}}
async function editAddressBookEntry(entry){if(!currentAddressBookPrinter||!entry)return;const name=prompt('Nombre del usuario:',entry.name??'');if(name===null)return;const payload={name:name.trim(),key_display:normalizeAddressBookPromptValue(prompt('Key Display:',entry.key_display??'')),freq:(prompt('Frecuente? (si/no):',entry.freq?'si':'no')||(entry.freq?'si':'no')).trim().toLowerCase()!=='no',title1:normalizeAddressBookPromptValue(prompt('Title 1:',entry.title1??'')),title2:normalizeAddressBookPromptValue(prompt('Title 2:',entry.title2??'')),title3:normalizeAddressBookPromptValue(prompt('Title 3:',entry.title3??'')),user_code:normalizeAddressBookPromptValue(prompt('User Code:',entry.user_code??'')),email_address:normalizeAddressBookPromptValue(prompt('E-mail Address:',entry.email_address??'')),folder:normalizeAddressBookPromptValue(prompt('Folder:',entry.folder??'')),status:normalizeAddressBookPromptValue(prompt('Status:',entry.status??'Activo'))||'Activo'};if(!payload.name){alert('El nombre es obligatorio.');return;}try{const response=await fetch(`/printers/${currentAddressBookPrinter.id}/address-book/${encodeURIComponent(entry.registration_no)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.detail||'No se pudo actualizar el usuario');await loadAddressBookEntries();}catch(error){alert(error.message||'No se pudo actualizar el usuario.');console.error(error);}}
async function deleteAddressBookEntry(registrationNo){if(!currentAddressBookPrinter)return;if(!confirm(`¿Eliminar el registro ${registrationNo}?`))return;try{const response=await fetch(`/printers/${currentAddressBookPrinter.id}/address-book/${encodeURIComponent(registrationNo)}`,{method:'DELETE'});const data=await response.json();if(!response.ok)throw new Error(data.detail||'No se pudo eliminar el usuario');await loadAddressBookEntries();}catch(error){alert(error.message||'No se pudo eliminar el usuario.');console.error(error);}}
function toggleCountersAuto(checked){if(checked)startCountersAuto();else stopCountersAuto();}
function startCountersAuto(){const iv=Number(document.getElementById('countersAutoInterval')?.value)||60;if(countersAutoTimer)clearInterval(countersAutoTimer);countersAutoTimer=setInterval(loadCounters,Math.max(5,iv)*1000);loadCounters();}
function stopCountersAuto(){if(countersAutoTimer){clearInterval(countersAutoTimer);countersAutoTimer=null;}}
async function loadCounters(){const list=document.getElementById('countersList');const lastEl=document.getElementById('countersLastUpdate');if(!list)return;try{list.innerHTML='<tr><td colspan="10">Actualizando contadores...</td></tr>';if(lastEl)lastEl.textContent='Actualizando...';const response=await fetch('/printers/counters');const data=await response.json();if(!Array.isArray(data)||!data.length){list.innerHTML='<tr><td colspan="10">No hay datos.</td></tr>';if(lastEl)lastEl.textContent='Última: -';return;}const fmt=value=>{if(value===null||value===undefined||value===''||value==='-')return '-';const n=Number(value);return Number.isNaN(n)?value:n.toLocaleString('es-CR');};list.innerHTML='';data.forEach(p=>{list.innerHTML+=`<tr><td>${p.name??'-'}</td><td>${p.serial??'-'}</td><td>${p.ip??'-'}</td><td>${fmt(p.total_pages)}</td><td>${fmt(p.copy_bw)}</td><td>${fmt(p.copy_color)}</td><td>${fmt(p.print_bw)}</td><td>${fmt(p.print_color)}</td><td>${fmt(p.bw_pages)}</td><td>${fmt(p.color_pages)}</td></tr>`;});if(lastEl)lastEl.textContent='Actualizado: '+new Date().toLocaleTimeString();}catch(error){list.innerHTML='<tr><td colspan="10">No se pudieron cargar los contadores.</td></tr>';if(lastEl)lastEl.textContent='Error';console.error('loadCounters error:',error);}}
async function loadInventory(){try{const response=await fetch('/inventory/');const data=await response.json();const list=document.getElementById('inventoryList');list.innerHTML='';if(!Array.isArray(data)||!data.length){list.innerHTML='<tr><td colspan="7">No hay inventario registrado.</td></tr>';return;}data.forEach(item=>{list.innerHTML+=`<tr><td>${item.id}</td><td>${item.name}</td><td>${item.model}</td><td>${item.type}</td><td>${item.quantity}</td><td>${item.min_stock}</td><td><button class="action-button action-button-danger" onclick="deleteInventory(${item.id})">Eliminar</button></td></tr>`;});}catch(error){console.error(error);}}
async function addInventoryItem(){const payload={name:document.getElementById('invName').value.trim(),model:document.getElementById('invModel').value.trim(),type:document.getElementById('invType').value,quantity:Number(document.getElementById('invQty').value),min_stock:Number(document.getElementById('invMin').value)};if(!payload.name||!payload.model||Number.isNaN(payload.quantity)||Number.isNaN(payload.min_stock)){alert('Completa todos los campos del inventario.');return;}try{await fetch('/inventory/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});document.getElementById('invName').value='';document.getElementById('invModel').value='';document.getElementById('invType').value='toner';document.getElementById('invQty').value='';document.getElementById('invMin').value='';loadInventory();}catch(error){alert('No se pudo agregar el inventario.');console.error(error);}}
async function deleteInventory(id){try{await fetch(`/inventory/${id}`,{method:'DELETE'});loadInventory();}catch(error){alert('No se pudo eliminar el inventario.');console.error(error);}}
async function loadTonerControl(){try{const response=await fetch('/toner-control/');const data=await response.json();const list=document.getElementById('tonerControlList');if(!list)return;list.innerHTML='';if(!Array.isArray(data)||!data.length){list.innerHTML='<tr><td colspan="18">No hay impresoras</td></tr>';return;}data.forEach(p=>{list.innerHTML+=`<tr><td>${p.shared_name??'-'}</td><td>${p.name??'-'}</td><td>${p.model??'-'}</td><td>${p.serial??'-'}</td><td><input value="${p.check_date??''}" id="check_${p.printer_id}"></td><td>${p.toner_black??'-'}</td><td>${p.is_color?(p.toner_cyan??'-'):'-'}</td><td>${p.is_color?(p.toner_magenta??'-'):'-'}</td><td>${p.is_color?(p.toner_yellow??'-'):'-'}</td><td><input type="number" value="${p.backup_black??0}" id="bk_${p.printer_id}"></td><td>${p.is_color?`<input type="number" value="${p.backup_cyan??0}" id="bc_${p.printer_id}">`:'-'}</td><td>${p.is_color?`<input type="number" value="${p.backup_magenta??0}" id="bm_${p.printer_id}">`:'-'}</td><td>${p.is_color?`<input type="number" value="${p.backup_yellow??0}" id="by_${p.printer_id}">`:'-'}</td><td>${p.location??'-'}</td><td><input value="${p.pedido??''}" id="pedido_${p.printer_id}"></td><td><input value="${p.work_order??''}" id="wo_${p.printer_id}"></td><td><input value="${p.notas??''}" id="notas_${p.printer_id}"></td><td><button class="action-button" onclick="saveBackup(${p.printer_id}, ${p.is_color})">Guardar</button></td></tr>`;});}catch(error){const list=document.getElementById('tonerControlList');if(list)list.innerHTML='<tr><td colspan="18">Error cargando datos</td></tr>';console.error('loadTonerControl error:',error);}}
async function saveBackup(id,isColor){const data={check_date:document.getElementById('check_'+id).value,backup_black:Number(document.getElementById('bk_'+id).value)||0,pedido:document.getElementById('pedido_'+id).value,work_order:document.getElementById('wo_'+id).value,notas:document.getElementById('notas_'+id).value};if(isColor){data.backup_cyan=Number(document.getElementById('bc_'+id).value)||0;data.backup_magenta=Number(document.getElementById('bm_'+id).value)||0;data.backup_yellow=Number(document.getElementById('by_'+id).value)||0;}try{await fetch(`/toner-control/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});alert('Guardado');loadTonerControl();}catch(error){alert('Error guardando backup');console.error(error);}}

function setTableFullHeight() {
    const header = document.querySelector('header');
    const filters = document.getElementById('dashboardFilters');
    const tableWrap = document.querySelector('#dashboardTableView .table-wrapper.dashboard-table-wrap');
    if (!tableWrap) return;
    const headerH = header ? header.getBoundingClientRect().height : 60;
    const filtersH = (filters && !filters.classList.contains('closed')) ? filters.getBoundingClientRect().height : 0;
    const extraTop = 20;
    const available = Math.max(320, window.innerHeight - headerH - filtersH - extraTop);
    tableWrap.style.height = available + 'px';
    tableWrap.style.maxHeight = available + 'px';
}
(function attachFilterListeners(){const searchEl=document.getElementById('searchInput');if(searchEl)searchEl.addEventListener('input',()=>loadPrinters());['viewMode','densityMode','statusFilter','typeFilter','errorFilter','sortFilter'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener('change',()=>loadPrinters());});const printerIpEl=document.getElementById('printerIp');if(printerIpEl){printerIpEl.addEventListener('input',()=>validatePrinterIpField());printerIpEl.addEventListener('blur',()=>{validatePrinterIpField();autofillPrinterNameFromIp();});printerIpEl.addEventListener('change',()=>{validatePrinterIpField();autofillPrinterNameFromIp();});}['discoverStartIp','discoverEndIp','discoverSingleIp'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener('input',()=>validateDiscoverFields());});toggleDiscoverModeFields();})();
showTab('dashboard');setDensityMode('standard');

